name: buiwd UwU kewnyew ^w^

on:
  workflow_dispatch:
  watch:
   types: [started]

defaults:
  run:
   shell: bash

jobs:
 buildtest:
    runs-on: ubuntu-latest

    steps:
      - name: checkout :3
        uses: actions/checkout@v2

      - name: set ;;w;; Swap >w< Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 5

      - name: setwup UwU pamckage >w<
        run: |
         sudo apt-get update -y && sudo apt-get install dialog bash sed wget git curl zip tar jq expect make cmake automake autoconf llvm lld lldb clang gcc binutils bison perl gperf gawk flex bc python3 zstd openssl unzip cpio bc bison build-essential ccache liblz4-tool libsdl1.2-dev libstdc++6 libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zlib1g-dev libncurses5-dev bzip2 git gcc g++ libssl-dev gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf gcc-arm-linux-gnueabi dos2unix kmod python2 -y

      - name: chweck cwang vewsion ^-^
        run: |
         clang -v

      - name: stawt >w< up >w<
        run: |
         ./build

      - name: anykewnyew ;;w;; ~ :3 zipping ^w^
        run: |
         git clone https://github.com/Frostleaft07/AnyKernel3 -b rmx1941 ~/any/ && \
         cp -r ~/out/arch/arm64/boot/Image.gz-dtb ~/any/ && \
         cd ~/any/ && zip -r9 omkegasRMX1941.zip *

      - name: upwoad ^w^ to ÚwÚ bashupwoad.com ^-^
        run: |
         curl bashupload.com -T omkegasRMX1941.zip
         sleep 3
         curl bashupload.com -T omkegasRMX1941.zip
         sleep 3
         curl bashupload.com -T omkegasRMX1941.zip
