name: Build test

on:
  workflow_dispatch:
  watch:
   types: [started]

defaults:
  run:
   shell: bash

jobs:
 buildtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with: 
          swap-size-gb: 5
         
      - name: setup package
        run: |
         ./ 

      - name: clean up
        run: |
         make clean; make mrproper; rm -rf out

      - name: check clang version
        run: |
         clang -v
         
      - name: start up
        run: |
         ./build

      - name: anykernel ~ zipping
        run: |
         git clone https://github.com/nathannxx/AnyKernel3 -b Nethunter ~/any/
         cp -r ~/out/arch/arm64/boot/Image.gz-dtb ~/any/
         cd ~/any/ && zip -r9 Nethengkertzy-${{ github.run_id }}.zip *
         
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
           files: |
            /home/runner/any/KernelSU*
           name: nethunter-test-no${{ github.run_id }}
           tag_name: ${{ github.run_id }}
        env:
         GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
